version: '3'

services:
  php:
    build:
      context: php
    volumes:
      - ../server:/var/www/server
      - ../worker:/var/www/worker
      - ../worker:/app/contracts
    ports:
      - 9000:8080